instagram/inst/urls.py
from django.urls import path
from inst import views
from django.conf.urls.static import static 
from django.conf import settings

app_name = 'inst'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_View, name="login_View"),
    path('signup/', views.signup_view, name="signup_view"),
    path('logout/', views.logout_view, name="logout_view"),

    path('update-profile/', views.update_profile, name='update_profile'),

    path('profile/', views.profile_view, name="profile_view"),
    path('create_post/', views.create_post, name='create_post'),


    path('change-password/', views.change_password, name='change_password'),


    path('story', views.story, name='story'),
    path('stories/', views.view_all_stories, name='view_all_stories'),
    
    path('add_comment/<int:post_id>/', views.add_comment, name='add_comment'),

    path('like/<int:post_id>/', views.toggle_like, name='toggle_like'),

    path('post/<int:post_id>/likes/', views.post_likes, name='post_likes'),

    path("notifications/", views.notifications, name="notifications"),

    path('profile/<str:username>/', views.user_profile_view, name='user_profile'),

    path('accept-follow-request/<int:request_id>/', views.accept_follow_request, name='accept_follow_request'),
    path('reject-follow-request/<int:request_id>/', views.reject_follow_request, name='reject_follow_request'),

    path('profile/<str:username>/followers/', views.followers_list, name='followers_list'),
    path('profile/<str:username>/following/', views.following_list, name='following_list'),

    path('messages/', views.message_list, name='messages'),
    path("chat/<str:username>/", views.chat_view, name="chat"),  # Chat with a user


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inst.urls')),
    
]

instagram/inst/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=255,blank=True,null=True)
    profile_pic = models.ImageField(upload_to='profile_pic/', blank=True)

    def __str__(self):
        return self.user.username

    @property
    def followers_count(self):
          # Count the number of followers for this profile
        return self.followers.count()

    @property
    def following_count(self):
        # Count the number of profiles this profile is following
        return self.following.count()

class Post(models.Model):
  author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')
  caption = models.TextField(max_length=255, blank=True)
  image = models.ImageField(upload_to='posts/')
  pub_date = models.DateTimeField(auto_now_add=True)

  class Meta:
    ordering = ['-pub_date']

  def __str__(self):
    return self.caption

class Story(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='stories')
    image = models.ImageField(upload_to='stories/')
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()

    def __str__(self):
        return f"Story by {self.author.user.username} created at {self.created_at}"
    

class Like(models.Model):
  user = models.ForeignKey(Profile, on_delete=models.CASCADE)
  post = models.ForeignKey(Post, on_delete=models.CASCADE)

  class Meta:
    unique_together = (
       ('user', 'post'),
       )

  def __str__(self):
    return f"{self.user.user.username} likes {self.post.author.user.username}'s post"
  
  def like_count(self):
        return self.like_set.count()
  
class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.user.username} comments: '{self.text}' on {self.post.caption}"
    
class FollowRequest(models.Model):
    sender = models.ForeignKey(User, related_name="sent_requests", on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name="received_requests", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=10,
        choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")],
        default="pending"
    )

    def __str__(self):
        return f"{self.sender} -> {self.receiver} ({self.status})"
    

class Following(models.Model):
  follower = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='following')
  following_user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='followers')

  class Meta:
    unique_together = (('follower', 'following_user'),)

  def __str__(self):
    return f"{self.follower.user.username} follows {self.following_user.user.username}"
  

class Message(models.Model):
  sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="sent_messages")
  receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="received_messages")
  text = models.TextField()
  timestamp = models.DateTimeField(auto_now_add=True)

  def __str__(self):
      return f"{self.sender.user.username} -> {self.receiver.user.username}: {self.text[:30]}"

instagram/inst/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile,Post,Story,Comment


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control input-1', 'placeholder': 'Username'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control input-2', 'placeholder': 'Password'})
    )

class SignupForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
    )

    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
    )

    password2 = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'})
    )

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'})
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']



class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = ['image']  # Include other fields as necessary

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['caption', 'image']
        widgets = {
            'caption': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Write a caption...'}),
        }



class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'profile_pic']



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

instagram/inst/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout 
from .forms import SignupForm, LoginForm,StoryForm,PostForm,ProfileUpdateForm,CommentForm
from django.contrib import messages
from .models import Post,Profile,Story,Like,FollowRequest,Following,Message
from django.utils import timezone
from datetime import timedelta
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.db.models import Max
from django.db.models import Exists, OuterRef
# Create your views here.
@login_required
def home(request):
    user_profile, created = Profile.objects.get_or_create(user=request.user)
    # Fetch all posts and annotate with whether the logged-in user has liked each post
    feeds = Post.objects.prefetch_related('comments', 'comments__user').annotate(
        liked_by_user=Exists(
            Like.objects.filter(user=request.user.profile, post=OuterRef('id'))
        )
    ).order_by('-pub_date')
    
    # Get the logged-in user's Profile instance
    user_profile = Profile.objects.get(user=request.user)
    
    # Get the latest story for the logged-in user
    user_story = Story.objects.filter(author=user_profile).order_by('-created_at').first()
    
    # Get the latest story for each other author
    latest_story_per_author = Story.objects.exclude(author=user_profile).values('author').annotate(latest_created_at=Max('created_at'))
    
    # Fetch the stories based on the latest created_at for each author
    other_stories = Story.objects.filter(
        author__in=[story['author'] for story in latest_story_per_author],
        created_at__in=[story['latest_created_at'] for story in latest_story_per_author]
    ).order_by('author', '-created_at')
    
    # Combine the logged-in user's story with the other stories
    stories = [user_story] if user_story else []
    stories.extend(other_stories)

    return render(request, 'inst/index.html', {'feeds': feeds, 'stories': stories})

def login_View(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('inst:home')
            else:
                # Return an 'invalid login' error message.
                messages.error(request, 'Invalid username or password.')
    else:
        form = LoginForm()
        
    return render(request, 'inst/login.html', {'form': form})

def signup_view(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created successfully!')
            return redirect('inst:login_View')
        else:
            for error in form.errors.values():
                messages.error(request, error)
    else:
        form = SignupForm()

    return render(request, 'inst/signup.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('inst:login_View')


@login_required
def story(request):
    if request.method=="POST":
        form = StoryForm(request.POST, request.FILES)
        if form.is_valid():
            new_story = form.save(commit = False)
            new_story.author = request.user.profile
            new_story.created_at = timezone.now()
            new_story.expires_at = timezone.now() + timedelta(hours=24)
            new_story.save()
            return redirect('inst:home')
    else:
        form = StoryForm()

    return render(request,'inst/story.html',{'form':form})
@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user.profile  # Set the current user's profile as the author
            post.save()
            messages.success(request, 'Your post has been uploaded successfully!')
            return redirect('inst:profile_view') 
        else:
            messages.error(request, 'There was an error uploading your post.')
    else:
        form = PostForm()

    return render(request, 'inst/post.html', {'form': form})



@login_required
def update_profile(request):
    print("Rendering update profile page")
    profile = request.user.profile
    
    if request.method == 'POST': 
        print("POST method triggered")
        form = ProfileUpdateForm(request.POST, request.FILES, instance=profile)
        print(request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated!')
            return redirect('inst:profile_view')
        else:
            print(form.errors)
    else:
        form = ProfileUpdateForm(instance=profile)
    
    return render(request, 'inst/update_profile.html', {'form': form})


def profile_view(request):
    # Get or create the profile for the logged-in user
    profile, created = Profile.objects.get_or_create(user=request.user)

    # Set default values if bio or profile_pic is null/empty
    if not profile.bio:
        profile.bio = "No bio added yet."
    if not profile.profile_pic:
        profile.profile_pic = "profile_pic/default_profile.jpg"  # Use a placeholder image path

    posts = Post.objects.filter(author=profile)

     # Include follower and following counts
    followers_count = profile.followers_count  # Dynamically calculated property
    following_count = profile.following_count  # Dynamically calculated property

# Get the list of followers and following
    followers_list = Following.objects.filter(following_user=profile).select_related('follower')
    following_list = Following.objects.filter(follower=profile).select_related('following_user')
    context = {
        'profile': profile,
        'posts': posts,
        'followers_count': followers_count,
        'following_count': following_count,
        'followers_list': followers_list,  # List of profiles following this user
        'following_list': following_list,  # List of profiles this user is following
    }

    return render(request, 'inst/profile.html', context)



@login_required
def change_password(request):
    if request.method == 'POST':
        current_password = request.POST.get('current_password')
        new_password = request.POST.get('new_password')
        confirm_password = request.POST.get('confirm_password')

        user = request.user

        # Check if the current password is correct
        if not user.check_password(current_password):
            messages.error(request, 'Current password is incorrect.')
            return redirect('inst:change_password')

        # Check if new password and confirm password match
        if new_password != confirm_password:
            messages.error(request, 'New password and Confirm password do not match.')
            return redirect('inst:change_password')

        # Update the user's password
        user.set_password(new_password)
        user.save()

        # Keep the user logged in after password change
        update_session_auth_hash(request, user)
        messages.success(request, 'Your password has been successfully changed!')
        return redirect('inst:profile_view')  # Redirect to the profile page or any other desired page

    return render(request, 'inst/password.html')



def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    print("Post fetched:", post)
    if request.method == "POST":
        print("POST data:", request.POST)
        form = CommentForm(request.POST)
        if form.is_valid():
            print("Form is valid")
            comment = form.save(commit=False)
            comment.user = request.user.profile  # Ensure this is correct
            comment.post = post
            comment.save()
            return redirect('inst:home')
        else:
            print("Form errors:", form.errors)
    return redirect('inst:home')


@login_required
def toggle_like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user_profile = request.user.profile  # Assuming a `Profile` model exists linked to the user.

    # Check if the user has already liked the post
    like, created = Like.objects.get_or_create(user=user_profile, post=post)

    if not created:
        # If the like already exists, remove it (unlike)
        like.delete()

    # Redirect back to the same page
    return redirect('inst:home')

@login_required
def post_likes(request, post_id):
    # Get the post and its likes
    post = get_object_or_404(Post, id=post_id)
    likes = post.like_set.select_related('user')

    # Pass the likes to the template
    return render(request, 'inst/post_likes.html', {'post': post, 'likes': likes})


@login_required
def view_all_stories(request):
    # Fetch all stories, ordered by creation time (latest first)
    stories = Story.objects.select_related('author').order_by('-created_at')

    # Get all stories for the logged-in user
    user_stories = stories.filter(author=request.user.profile)
    # Get all other stories except the logged-in user's
    other_stories = stories.exclude(author=request.user.profile)

    context = {
        "user_stories": user_stories,
        "other_stories": other_stories,
    }
    return render(request, "inst/view_all_stories.html", context)

@login_required
def notifications(request):
    # Get all pending follow requests for the logged-in user
    follow_requests = FollowRequest.objects.filter(receiver=request.user, status="pending").order_by("-created_at")

    print(follow_requests)  # Debugging: Print the queryset to ensure it's not empty

instagram/inst/templates/inst/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default Title{% endblock title %}</title>

</head>
<body>
    {% include "inst/nav.html" %}  <!-- Navigation bar -->
    
    <main>
        {% block content %}
        <!-- Content from child templates will be rendered here -->
        {% endblock content %}
    </main>
    
    <footer>
        <!-- Optional footer -->
    </footer>
</body>
</html>

instagram/inst/templates/inst/followers_list.html
{% extends "inst/base.html" %}
{% block content %}
<h3>{{ profile.user.username }}'s Followers</h3>
<ul>
    {% for follower in followers %}
        <li>
            <a href="{% url 'inst:user_profile' follower.user.username %}">
                <img src="{{ follower.profile_pic.url }}" alt="Profile Picture" style="width: 40px; height: 40px; border-radius: 50%;"> 
                {{ follower.user.username }}
            </a>
        </li>
    {% empty %}
        <p>No followers yet.</p>
    {% endfor %}
</ul>
<a href="{% url 'inst:user_profile' profile.user.username %}">Back to Profile</a>
{% endblock %}

instagram/inst/templates/inst/following_list.html
{% extends "inst/base.html" %}
{% block content %}
<h3>{{ profile.user.username }}'s Following</h3>
<ul>
    {% for user in following %}
        <li>
            <a href="{% url 'inst:user_profile' user.user.username %}">
                <img src="{{ user.profile_pic.url }}" alt="Profile Picture" style="width: 40px; height: 40px; border-radius: 50%;"> 
                {{ user.user.username }}
            </a>
        </li>
    {% empty %}
        <p>Not following anyone yet.</p>
    {% endfor %}
</ul>
<a href="{% url 'inst:user_profile' profile.user.username %}">Back to Profile</a>
{% endblock %}

instagram/inst/templates/inst/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Overpass+Mono" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'inst/login_style.css' %}">
    <title>Login</title>
  </head>
  <body>

    <div id="wrapper">
      <div class="main-content">
        <div class="header">
          <img src="https://i.imgur.com/zqpwkLQ.png" />
        </div>
        <div class="l-part">
          <form method="post" class="login-form">
            {% csrf_token %}
            <div class="form-group">
              {{ form.username }}  <!-- Renders username field -->
              {{ form.username.errors }} 
            </div>
            <div class="form-group overlap-text">
              {{ form.password }}  <!-- Renders password field -->
              {{ form.password.errors }} 
            </div>
            <button type="submit" class="btn btn-primary">Log in</button>
          </form>
          {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %} mt-3" role="alert">
                  {{ message }}
              </div>
          {% endfor %}
      {% endif %}
        </div>
      </div>
      <div class="sub-content">
        <div class="s-part">
          Don't have an account? <a href="{% url 'inst:signup_view' %}">Sign up</a>
        </div>
      </div>
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

instagram/inst/templates/inst/message_list.html
{% extends "inst/base.html" %}
{% block content %}
<div class="container mt-4">
    <h2>Messages</h2>
    <p>Only users who follow each other can chat.</p>

    <!-- Sidebar: Mutual Followers -->
    <div class="row">
        <div class="col-md-4 border-right">
            <h4 class="p-3">Chats</h4>
            <ul class="list-group list-group-flush">
                {% for user in mutual_followers %}
                <li class="list-group-item d-flex align-items-center">
                    <img src="{{ user.profile_pic }}" class="rounded-circle mr-2" width="40" height="40" alt="User">
                    <a href="{% url 'inst:chat' user.username %}" class="text-dark text-decoration-none">
                        {{ user.username }}
                    </a>
                </li>
                {% empty %}
                <p class="p-3 text-muted">No mutual followers to chat with.</p>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

instagram/inst/templates/inst/notifications.html
{% for request in follow_requests %}
    <div>
        <p>{{ request.sender.username }} wants to follow you.</p>
        <form method="POST" action="{% url 'inst:accept_follow_request' request.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Accept</button>
        </form>
        <form method="POST" action="{% url 'inst:reject_follow_request' request.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Reject</button>
        </form>
    </div>
{% empty %}
    <p>No follow requests.</p>
{% endfor %}

instagram/inst/templates/inst/profile.html
{% extends "inst/base.html" %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% block title %} 
Profile
    {% endblock title %}
  </head>
  <body>
{% block content %}
    <section class="vh-100">
        <div class="container py-5 h-50">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-md-9 col-lg-7 col-xl-5">
              <div class="card" style="border-radius: 15px;">
                <div class="card-body p-4">
                  <div class="d-flex text-black">
                    <div class="flex-shrink-0">
                    <img src="{{  profile.profile_pic.url }}" alt="Upload Photo Here" class="img-fluid" style="width: 180px; height:200px ; border-radius: 10px;object-fit: cover;">
                    </div>
                    <div class="flex-grow-1 ms-3">
                        <h5 class="ml-3 d-inline-block">{{ profile.user.username }}</h5>
                      <div class="d-flex justify-content-start rounded-3 p-2 m-3" style="background-color: #efefef;">
                        <div>
                          <p class="small text-muted mb-1">Following</p>
                          <p class="mb-0 ml-3"><a href="{% url 'inst:following_list' profile.user.username %}">{{ following_count }}</a></p>
                        </div>
                        <div class="px-3">
                          <p class="small text-muted mb-1">Followers</p>
                          <p class="mb-0 ml-3"><a href="{% url 'inst:followers_list' profile.user.username %}">{{ followers_count }}</a></p>
                        </div>
                      </div>
                      <div class="d-flex pt-1 ml-3 mr-3">
                        
                      </div>
                    </div>
                    
                  </div>
                  {{ profile.bio }}
                </div>
              </div>
            </div>
          </div>
        </div>
        <p class="text-center">POST</p>
      </section>
      <hr>

      <div class="container">
        <div class="row">
          {% for post in posts %}
          <div class="col-md-3">
            <div class="card mb-3">
              <img class="card-img-top img-fluid" src="{{ post.image.url }}" alt="Card image cap" style="width: 100%; height: 220px;object-fit: cover;">
              <div class="card-body">
                <h5 class="card-title">{{ post.author.user.username }}</h5>
                <p class="card-text">{{ post.caption }}</p>
                <p class="card-text"><small class="text-muted">Posted on {{ post.pub_date }}</small></p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      {% endblock content %}

instagram/inst/templates/inst/user_profile.html
{% extends "inst/base.html" %}
{% load static %}

{% block content %}
<section class="vh-100">
    <div class="container py-5 h-50">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-md-9 col-lg-7 col-xl-5">
                <div class="card" style="border-radius: 15px;">
                    <div class="card-body p-4">
                        <div class="d-flex text-black">
                            <div class="flex-shrink-0">
                                <img src="{{ profile.profile_pic.url }}" alt="Upload Photo Here" class="img-fluid" style="width: 180px; height:200px; border-radius: 10px; object-fit: cover;">
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <h5 class="ml-3 d-inline-block">{{ profile.user.username }}</h5>
                                <div class="d-flex justify-content-start rounded-3 p-2 m-3" style="background-color: #efefef;">
                                    <div>
                                        <p class="small text-muted mb-1">Following</p>
                                        <p class="mb-0 ml-3">
                                          <a href="{% url 'inst:following_list' profile.user.username %}">{{ following_count }}</a>
                                        </p>
                                    </div>
                                    <div class="px-3">
                                        <p class="small text-muted mb-1">Followers</p>
                                        <p class="mb-0 ml-3">
                                          <a href="{% url 'inst:followers_list' profile.user.username %}">{{ followers_count }}</a>
                                        </p>
                                    </div>
                                </div>
                                <div class="d-flex pt-1 ml-3 mr-3">
                                  {% if show_follow_button %}
                                  <form method="POST" action="{% url 'inst:user_profile' profile.user.username %}">
                                      {% csrf_token %}
                                      <button type="submit" class="btn btn-primary flex-grow-1">Follow</button>
                                  </form>
                                  {% elif follow_request_sent %}
                                  <p class="text-warning">Follow request sent.</p>
                                  {% elif is_following %}
                                  <p class="text-success">You are following {{ profile.user.username }}.</p>
                                  {% endif %}
                              </div>
                            </div>
                        </div>
                        <p>{{ profile.bio }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h5 class="text-center mt-4">Posts</h5>
</section>
<hr>

<div class="container">
    <div class="row">
        {% for post in posts %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <img class="card-img-top img-fluid" src="{{ post.image.url }}" alt="Card image cap" style="width: 100%; height: 220px; object-fit: cover;">
                <div class="card-body">
                    <h5 class="card-title">{{ post.author.user.username }}</h5>
                    <p class="card-text">{{ post.caption }}</p>
                    <p class="card-text">
                        <small class="text-muted">Posted on {{ post.pub_date|date:"F d, Y H:i" }}</small>
                    </p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-12">
            <p class="text-center">No posts available.</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}